// <auto-generated />
namespace Multi_language.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201609041819327_AutomaticMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201609041819327_AutomaticMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201609041820071_201609041819327_AutomaticMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
